build:
  image: guangie88/rust:1.33.0
  stage: build
  script:
  - cargo build -v --locked --all
  only:
    changes:
    - cli/**/*
    - lib/**/*
    - Cargo.lock
    - Cargo.toml
    refs:
    - master
    - merge_requests

test:
  image: guangie88/rust:1.33.0
  stage: test
  script:
  - rustfmt --check cli/**/*.rs lib/**/*.rs
  - cargo clippy -v --locked --all
  - cargo test -v --locked --all
  only:
    changes:
    - cli/**/*
    - lib/**/*
    - Cargo.lock
    - Cargo.toml
    refs:
    - master
    - merge_requests

build-end:
  image: alpine:3.9
  stage: build-end
  script:
  - "true"
  only:
    refs:
    - merge_requests

.build-release:
  image: clux/muslrust:stable
  stage: build-release
  before_script:
  - mkdir -p artifacts/original
  script:
  - cargo build -v --locked --release --all
  after_script:
  - cp target/x86_64-unknown-linux-musl/release/smv artifacts/original/smv_${OS}_${ARCH}
  artifacts:
    paths:
    - artifacts/original/smv_${OS}_${ARCH}
  only:
    refs:
    - master
    - /^v\d+\.\d+\.\d+(-\S*)?$/

build-release:linux_amd64:
  variables:
    OS: linux
    ARCH: amd64
  extends: .build-release

.upload-release:
  image: alpine:3.9
  stage: upload-release
  before_script:
  - mkdir -p artifacts/compressed
  # upx installation
  - wget https://github.com/upx/upx/releases/download/v3.95/upx-3.95-${ARCH}_${OS}.tar.xz
  - tar xvf upx-3.95-${ARCH}_${OS}.tar.xz
  - mv upx-3.95-${ARCH}_${OS}/upx /usr/local/bin/
  - rm -r upx-3.95-${ARCH}_${OS} upx-3.95-${ARCH}_${OS}.tar.xz
  # ghr installation
  - wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_${OS}_${ARCH}.tar.gz
  - tar xvf ghr_v0.12.0_${OS}_${ARCH}.tar.gz
  - mkdir -p /tmp/bin/
  - mv ghr_v0.12.0_${OS}_${ARCH}/ghr /usr/local/bin/
  - rm -r ghr_v0.12.0_${OS}_${ARCH} ghr_v0.12.0_${OS}_${ARCH}.tar.gz
  - apk add --no-cache ca-certificates
  # Copy to another artifact path
  - cp artifacts/original/smv_${OS}_${ARCH} artifacts/compressed/smv_${OS}_${ARCH}
  script:
  - upx --best artifacts/compressed/smv_${OS}_${ARCH}
  - ghr -t ${GITHUB_TOKEN} -u ${GITHUB_USER} -r ${GITHUB_REPONAME} -c ${CI_COMMIT_SHA} -replace ${CI_COMMIT_REF_NAME} artifacts/compressed/smv_${OS}_${ARCH}
  artifacts:
    paths:
    - artifacts/compressed/smv_${OS}_${ARCH}
  only:
    refs:
    - /^v\d+\.\d+\.\d+(-\S*)?$/

upload-release:linux_amd64:
  variables:
    OS: linux
    ARCH: amd64
  dependencies:
  - build-release:linux_amd64
  extends: .upload-release

stages:
- build
- test
- build-end
- build-release
- upload-release

cache:
  key: all-share
  paths:
  - target/
