version: '1.0'
stages:
- build-base
- build-test
- test
- release

steps:
  build_base_image:
    type: build
    stage: build-base
    title: Build base target Docker image
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: base
    target: base
  
  build_test:
    type: parallel
    stage: build-test
    steps:
      build_test:
        type: build
        title: Build test image
        image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        tag: test
        target: test

      build:
        type: build
        title: Build image in debug mode
        image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        tag: build
        target: build

  run_test:
    title: Run tests
    stage: test
    image: ${{build_test}}
    # working_directory: ${{main_clone}}
    commands:
    - rustfmt --check cli/**/*.rs lib/**/*.rs
    - cargo clippy -v --locked --all
    - cargo test -v --locked --all

  build_release:
    type: build
    stage: release
    title: Build release image containing binary
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BRANCH}}
    target: release
