version: '1.0'
mode: parallel
stages:
- test-release

steps:
  build_test:
    type: build
    title: Build test image
    dockerfile: Dockerfile-test
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: test
    target: test
    when:
      steps:
      - name: main_clone
        on:
        - success

  test:
    title: Run tests
    stage: test-release
    image: ${{build_test}}
    working_directory: ${{main_clone}}
    commands:
    - cargo fmt -v --all -- --check
    - cargo clippy -v --locked --all
    - cargo test -v --locked --all
    when:
      steps:
      - name: build_test
        on:
        - success

  build_release:
    type: build
    stage: test-release
    title: Build release image containing binary
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BRANCH}}
    target: release
    when:
      steps:
      - name: main_clone
        on:
        - success
