version: '1.0'
mode: parallel
stages:
- test
- native-release
- docker-release

steps:
  build_test:
    type: build
    title: Build test image
    dockerfile: Dockerfile-test
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: test
    when:
      steps:
      - name: main_clone
        on:
        - success

  test:
    title: Run tests
    stage: test
    image: ${{build_test}}
    working_directory: ${{main_clone}}
    commands:
    - cargo fmt -v --all -- --check
    - cargo clippy -v --locked --all
    - cargo test -v --locked --all
    when:
      steps:
      - name: build_test
        on:
        - success

  build_release:
    title: Build release
    stage: native-release
    image: clux/muslrust:stable
    working_directory: ${{main_clone}}
    commands:
    - cargo build --release -v --locked --all
    when:
      steps:
      - name: main_clone
        on:
        - success

  compress_release:
    title: Compress release executable
    stage: native-release
    image: guangie88/releaser:alpine_upx-3_ghr-0.12
    working_directory: ${{main_clone}}
    commands:
    - mkdir -p target/x86_64-unknown-linux-musl/release-compressed
    - cd target/x86_64-unknown-linux-musl
    - upx --best release/smv release-compressed/smv_linux_amd64
    when:
      steps:
      - name: build_release
        on:
        - success

  upload_release:
    title: Upload release executable
    stage: native-release
    image: guangie88/releaser:alpine_upx-3_ghr-0.12
    working_directory: ${{main_clone}}/target/x86_64-unknown-linux-musl/release-compressed
    commands:
    - |-
      ghr -u ${{CF_REPO_OWNER}} -r ${{CF_REPO_NAME}} \
          -c ${{CF_REVISION}} -replace ${{CF_BRANCH}} smv_linux_amd64
    when:
      branch:
        only:
        - /^v\d+\.\d+\.\d+(-\S*)?$/
      steps:
      - name: compress_release
        on:
        - success

  build_docker_release:
    type: build
    stage: docker-release
    title: Build release image containing binary
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BRANCH}}
    target: release
    when:
      steps:
      - name: main_clone
        on:
        - success
