version: '1.0'
stages:
- build-common
- build-test-release

steps:
  build_common_image:
    type: build
    stage: build-common
    title: Build common target Docker image
    image-name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    target: common
  
  parallel_build_run_test:
    type: parallel
    stage: build-test-release
    steps:
      build_test:
        type: build
        title: Build test image and run tests
        image-name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        target: test
      run_test:
        type: freestyle
        title: Run tests
        image: ${{build_test}}
        # working_directory: ${{main_clone}}
        commands:
        - rustfmt --check cli/**/*.rs lib/**/*.rs
        - cargo clippy -v --locked --all
        - cargo test -v --locked --all
        when:
          steps: 
          - name: build_test
            on:
            - success

      build:
        type: build
        title: Build image in debug mode
        image-name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        target: build

      build_release:
        type: build
        title: Build release image containing binary
        image-name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        tag: ${{CF_BRANCH}}
        target: release
